# Generated by Django 6.0 on 2025-12-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('web_adresi', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('affiliate_link', models.URLField()),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.magaza')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyatlar', to='urunler.urun')),
            ],
        ),
    ]
