# Generated by Django 6.0 on 2025-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='urun_resimleri/'),
        ),
    ]
