# Generated by Django 5.2.7 on 2025-12-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_yorum_alter_fiyat_id_alter_magaza_id_alter_urun_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta (isteğe bağlı)'),
        ),
        migrations.AddField(
            model_name='yorum',
            name='onayli',
            field=models.BooleanField(default=False, verbose_name='Onaylı mı?'),
        ),
        migrations.AddField(
            model_name='yorum',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon (isteğe bağlı)'),
        ),
    ]
