# Generated by Django 5.2.6 on 2026-01-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_clicklog_urun_alter_clicklog_id_alter_fiyat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim_url',
            field=models.URLField(blank=True, help_text='Resim URL (yer kaplamaz)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='urunresim',
            name='resim_url',
            field=models.URLField(blank=True, help_text='Resim URL (yer kaplamaz)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='urunresim',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='urun_resimleri/'),
        ),
    ]
