# Generated by Django 5.2.6 on 2026-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_clicklog_urun_alter_clicklog_id_alter_fiyat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyat',
            name='para_birimi',
            field=models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'ABD Doları ($)')], default='TL', help_text='Fiyat hangi para biriminde', max_length=3),
        ),
        migrations.AddField(
            model_name='urun',
            name='resim_url',
            field=models.URLField(blank=True, help_text='Resim URL (yer kaplamaz)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='urunresim',
            name='resim_url',
            field=models.URLField(blank=True, help_text='Resim URL (yer kaplamaz)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='urunresim',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='urun_resimleri/'),
        ),
    ]
