# Generated by Django 6.0 on 2026-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_fiyat_para_birimi_urun_resim_url_urunresim_resim_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='subid',
            field=models.CharField(blank=True, help_text='Alt kimlik (ör: otomatik_0, admin, vs.)', max_length=100, null=True),
        ),
    ]
