# Generated by Django 6.0 on 2026-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_urun_resim_url_UrunResim_resim_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyat',
            name='para_birimi',
            field=models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'ABD Doları ($)')], default='TL', help_text='Fiyat hangi para biriminde', max_length=3),
        ),
    ]
