# Generated by Django 5.2.6 on 2026-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_clicklog_subid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun_kodu',
            field=models.CharField(blank=True, help_text='Kısa arama kodu (otomatik)', max_length=12, null=True, unique=True),
        ),
    ]
