# Generated by Django 5.2.6 on 2026-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_urun_urun_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyat',
            name='gonderim_durumu',
            field=models.BooleanField(default=True, help_text='Gönderilebiliyor mu?'),
        ),
        migrations.AddField(
            model_name='fiyat',
            name='gonderim_ucreti',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kargo ücreti', max_digits=10),
        ),
        migrations.AddField(
            model_name='fiyat',
            name='gonderim_yerinden',
            field=models.CharField(default='Çin', help_text='Hangi ülkeden gönderiliyor', max_length=100),
        ),
    ]
