# Generated by Django 6.0 on 2026-02-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_fiyat_gonderim_durumu_fiyat_gonderim_ucreti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='source_url',
            field=models.URLField(blank=True, help_text='Ürünün kaynak URL adresi (tekrarları önler)', max_length=500, null=True, unique=True),
        ),
    ]
