# Generated by Django 5.2.6 on 2026-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0011_urun_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='alt_baslik',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık'),
        ),
        migrations.AddField(
            model_name='urun',
            name='ana_baslik',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ana Başlık'),
        ),
        migrations.AddField(
            model_name='urun',
            name='etiketler',
            field=models.CharField(blank=True, max_length=500, verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='urun',
            name='ozellikler',
            field=models.TextField(blank=True, verbose_name='Özellikler'),
        ),
    ]
