# Generated by Django 5.2.6 on 2026-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0012_urun_alt_baslik_urun_ana_baslik_urun_etiketler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiyat',
            name='affiliate_link',
            field=models.URLField(max_length=1000),
        ),
    ]
