# Generated by Django 5.2.6 on 2026-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0013_alter_fiyat_affiliate_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='source_url',
            field=models.URLField(blank=True, help_text='Ürünün kaynak URL adresi (tekrarları önler)', max_length=1000, null=True, unique=True),
        ),
    ]
