# Generated by Django 5.2.7 on 2026-02-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0014_alter_urun_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='sira',
            field=models.PositiveIntegerField(default=0, help_text='Ürün sırası (küçükten büyüğe önde)'),
        ),
    ]
