# Generated by Django 5.2.7 on 2026-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0015_urun_sira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='sira',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Ürün sırası (küçükten büyüğe önde)', null=True),
        ),
    ]
