# Generated by Django 5.2.6 on 2026-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0016_alter_urun_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='item_id',
            field=models.CharField(blank=True, help_text='eBay ürün ID', max_length=50, null=True, unique=True),
        ),
    ]
