# Generated by Django 5.2.6 on 2026-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0017_urun_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='durum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Durum'),
        ),
    ]
