# Generated by Django 5.2.6 on 2026-03-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0019_fiyat_ucretsiz_kargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Kategori URL kimligi (or. retro-handheld)', max_length=80, unique=True)),
                ('isim', models.CharField(max_length=120)),
                ('alanlar', models.JSONField(blank=True, default=list, help_text='Kategoriye ozel alan semasi')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategori Semasi',
                'verbose_name_plural': 'Kategori Semalari',
            },
        ),
        migrations.AddField(
            model_name='urun',
            name='detaylar',
            field=models.JSONField(blank=True, default=dict, help_text='Kategori semasina gore yapisal urun alanlari'),
        ),
        migrations.AddField(
            model_name='urun',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urunler', to='urunler.kategorisema'),
        ),
    ]
