# Generated by Django 5.2.6 on 2026-03-24 07:25

from django.db import migrations
from django.utils.text import slugify


def fill_missing_slugs(apps, schema_editor):
    Urun = apps.get_model('urunler', 'Urun')
    existing = set(Urun.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))

    for urun in Urun.objects.filter(slug__isnull=True) | Urun.objects.filter(slug=''):
        base_text = urun.ana_baslik or urun.isim or urun.urun_kodu or f'urun-{urun.id}'
        base_slug = slugify(base_text)[:230] or f'urun-{urun.id}'
        candidate = base_slug
        i = 2
        while candidate in existing:
            candidate = f"{base_slug[:220]}-{i}"
            i += 1
        urun.slug = candidate
        urun.save(update_fields=['slug'])
        existing.add(candidate)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0020_kategorisema_urun_detaylar_urun_slug_urun_kategori'),
    ]

    operations = [
        migrations.RunPython(fill_missing_slugs, noop_reverse),
    ]
