# Generated by Django 5.2.6 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0021_backfill_urun_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='ana_baslik',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ana Başlık'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='alt_baslik',
            field=models.CharField(blank=True, max_length=500, verbose_name='Alt Başlık'),
        ),
    ]
