# Generated by Django 5.2.6 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0022_alter_urun_baslik_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='client_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='gclid',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='landing_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='referrer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='utm_source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
